### ISSUE TITLE
Delivery should NOT delete its license

### ISSUE THREAD

**Issue by binamov** [chef-cft/wombat#159]
Right now cookbooks/delivery/default.rb deletes the delivery license at the end:
https://github.com/chef-cft/wombat/blob/master/cookbooks/delivery/recipes/default.rb#L126-L128

This makes wrapping around wombat unnecessarily complex:
- no longer can i rely on packer/keys to store all of my keys for build
- instead i have to put the license into yet another place and bring it in with my wrapper

The license deletion onus should be on the wrapper-consumer of wombat, eg. in sales demo use case or POC use case or training use case it's totally OK NOT to delete the license.

@andrewelizondo @tpetchel

**Comment by tpetchel** [comment]
A few thoughts:
- For the Learn Chef tutorial, there is no wrapper cookbook/process - we simply run wombat and give the user the CFN template.
- A side-effect of not deleting the license is that the generated AMI will have a functioning license. Depending on which license file was used to run wombat, users could potentially have full, unlimited access to a system.

I see a trade-off in complexities here - if we delete the license file, it creates work for the wrapper-consumer. If we don't delete the license file, it creates work for direct consumers, e.g. Learn Chef.

You might argue that we should use a temporary license to run wombat, which is fair. But I still don't want a valid license file on the AMI. We really want folks to get a eval key from us so that they're registered in the system.

Thoughts on a solution that satisfies all requirements?

**Comment by tpetchel** [comment]
Just a thought - can your wrapper process simply scp a license key over and reconfigure?

**Comment by binamov** [comment]
I can cookbook_file/remote_file the license in, meaning I'll have to put it in yet another place beyond packer/keys. Learn Chef should also be a wrapper-consumer of wombat @tpetchel .

**Comment by tpetchel** [comment]
I still don't like the idea of leaving the key on a potentially public AMI - it happened once before and we had to scramble to fix folks.

By deleting the key, you're asking me to wrap wombat and solve the problem. I don't have that requirement, nor the time to implement this right now.

That said, I don't want you to be blocked. If you need this functionality to move forward, I say go ahead and make the change and I'll deal with it the next time I need to rev the tutorial AMIs.

Would love thoughts from @andrewelizondo @cheeseplus.

**Comment by binamov** [comment]
so maybe key deletion needs to be part of the packer job that AMIs the instance, AFTER chef converges? The current setup addresses only the Learn Chef use case, making wombat less of a reusable library.

**Comment by tpetchel** [comment]
I talked with @andrewelizondo offline. I'm OK now with not deleting the license key because the base AMIs generated by wombat are guaranteed to stay private. Andre agreed to help create the wrapper for Learn Chef in the near future.

Thanks for talking it through.

(Edited)
